# ~/suehiro/.vim/.dein.toml

# utilities
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  let g:airline#extensions#branch#enabled = 1
  nnoremap [fugitive]  <Nop>
  nmap <space>g [fugitive]
  nnoremap <silent> [fugitive]s :Gstatus<CR><C-w>T
  nnoremap <silent> [fugitive]a :Gwrite<CR>
  nnoremap <silent> [fugitive]c :Gcommit-v<CR>
  nnoremap <silent> [fugitive]b :Gblame<CR>
  nnoremap <silent> [fugitive]p :Gpull<CR>
  nnoremap <silent> [fugitive]d :Gdiff<CR>
  nnoremap <silent> [fugitive]m :Gmerge<CR>
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'kien/ctrlp.vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'junegunn/vim-peekaboo'

[[plugins]]
repo = 'mhinz/vim-signify'

[[plugins]]
repo = 'CoatiSoftware/vim-sourcetrail'


# editing
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  set laststatus=2
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#buffer_idx_mode = 1
  let g:airline#extensions#whitespace#mixed_indent_algo = 1
  let g:airline_theme = 'dark'
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'machakann/vim-sandwich'


# completion and linting
[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
    \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
'''
merged = 0

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'ledger/vim-ledger'


# colorschemes
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
  au MyAutoCmd VimEnter * nested colorscheme gruvbox
'''

[[plugins]]
repo = 'crusoexia/vim-monokai'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme monokai
'''
