# ~/suehiro/.vim/.dein_lazy.toml
[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo   = 'Shougo/unite.vim'

[[plugins]]
repo = 'tacroe/unite-mark'
on_source = ['unite.vim']

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
on_source = ['unite.vim']

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'junegunn/gv.vim'
on_cmd = ['GV']

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTree', 'NERDTreeToggle', 'NERDTreeFind']

[[plugins]]
repo = 'junegunn/gv.vim'
on_cmd = ['GV']

[[plugins]]
repo = 'Yilin-Yang/vim-markbar'
on_map = ['<Plug>ToggleMarkbar']

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = ['<Plug>(EasyAlign)']
on_cmd = ['EasyAlign']

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = ['TagbarToggle']

[[plugins]]
repo = 'mbbill/undotree'
on_cmd = ['UndotreeToggle']

# filetypes
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

[[plugins]]
repo = 'elzr/vim-json'
hook_add = 'let g:vim_json_syntax_conceal = 0'
on_ft = ['json']

[[plugins]]
repo  = 'phpactor/phpactor'
on_ft = ['php']
build = 'composer install'

[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = ['yaml']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html','vue']
hook_add = '''
  let g:html5_event_handler_attributes_complete = 1
  let g:html5_rdfa_attributes_complete = 1
  let g:html5_microdata_attributes_complete = 1
  let g:html5_aria_attributes_complete = 1
'''
[[plugins]]
repo  = 'phpactor/phpactor'
on_ft = ['php']
build = 'composer install'

[[plugins]]
repo = 'StanAngeloff/php.vim'
on_ft = ['php']

[[plugins]]
repo = '2072/PHP-Indenting-for-VIm'
on_ft = ['php']

[[plugins]]
repo = 'neomake/neomake'
