# ~/suehiro/.vim/.dein.toml
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo   = 'Shougo/unite.vim'

[[plugins]]
repo = 'tacroe/unite-mark'
on_source = ['unite.vim']

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
on_source = ['unite.vim']

[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#[[plugins]]
#repo  = 'Quramy/tsuquyomi'
#on_ft = ['typescript']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'crusoexia/vim-monokai'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'kien/ctrlp.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'plasticboy/vim-markdown'
